engine:
  type: "in_memory"
  partitions_number: 100
network:
  host: "127.0.0.1"
  port: "8081"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "info"
  output: "/log/output.log"