engine:
  type: "in_memory"
  partitions_number: 100
network:
  host: "127.0.0.1"
  port: "8081"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "info"
  output: "/log/output.log"
wal:
  flushing_batch_size: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "./data/wal"
replication:
  replica_type: "master"
  master_address: "127.0.0.1:8082"
  sync_interval: "1s"