name: E2E tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go build -o storage_server ./cmd/server/server.go
          go test ./test/e2e/...